In [ ]:
why numpy?
memory:numpy data structure takes up less space
performance:it is more speed and faster than lists
functionality:scipy & numpy have optimized functions such as linear algebra operations built in.

In [1]:
#declaring a list of 10 elements
import numpy as np
import sys
s=[0,1,2,3,4,5,6,7,8,9]
print("size of each element of list in bytes:",sys.getsizeof(s))
print("size of the whole list in bytes:",sys.getsizeof(s)*len(s))

size of each element of list in bytes: 136
size of the whole list in bytes: 1360


In [5]:
#declaring a numpy array of 10 elements
import numpy as np
import sys
D=np.array([0,1,2,3,4,5,6,7,8,9])
print("size of each element of the numpy array in bytes:",D.itemsize)
print("size of the whole numpy array in bytes:",D.size*D.itemsize)

size of each element of the numpy array in bytes: 4
size of the whole numpy array in bytes: 40


In [6]:
#performance
import numpy as np
import time
#size of arrays and lists
size = 10000000
#declaring lists
list1=range(size)
list2=range(size)
#declaring arrays
array1=np.arange(size)
array2=np.arange(size)
#capturing time befor the multiplication of python list
initialTime=time.time()
#multiplying elements of both the lists and stored in another list
resultantList=[(a*b) for a, b in zip(list1, list2)]
#calculating execution time
print("Time taken by Lists to perform multiplication:",(time.time()-initialTime)*1000,"milliseconds")
#capturing time before the numpy multiplicataion of numpy arrays
initialtime=time.time()
#multiplying elements of both the numpy arrays and stored in another numpy array
resultantArray=array1*array2
#calculating execution time
print("Time taken by Lists to perform multiplication:",(time.time()-initialTime)*1000,"milliseconds")





Time taken by Lists to perform multiplication: 2322.0624923706055 milliseconds
Time taken by Lists to perform multiplication: 2354.1810512542725 milliseconds


In [7]:
np.ones(3)

array([1., 1., 1.])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
import numpy as np
np.random.random(3)

array([0.53603508, 0.23753654, 0.05698711])

In [25]:
#Slicing 1D arrasys
data=np.array([1,2,3])
data[0]

1

In [26]:
data[1]

2

In [27]:
data[0:2]

array([1, 2])

In [28]:
data[1:]

array([2, 3])

In [22]:
#Slicing 2D arrays
data=np.array([[1,2],[3,4],[5,6]])
data[0,1]

2

In [31]:
data[1:3]

array([2, 3])

In [35]:
data=np.array([[1,2],[3,4],[5,6]])
data[0:2,0]

array([1, 3])

In [36]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [37]:
data[1:3,1]

array([4, 6])

In [38]:
data[0:3,1]

array([2, 4, 6])

In [39]:
data[0:0]

array([], shape=(0, 2), dtype=int32)

In [40]:
#slicing 3d array
a=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print(a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [41]:
print(a[0:2])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [45]:
print(a[0:2,1:])

[[[ 3  4]
  [ 5  6]]

 [[ 9 10]
  [11 12]]]


In [46]:
print(a[0:2,1:,1:])

[[[ 4]
  [ 6]]

 [[10]
  [12]]]


In [47]:
print(a[0:2,1:,1:])

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed